var hierarchy =
[
    [ "IA_XML_Atlas", "d9/dca/struct_i_a___x_m_l___atlas.html", null ],
    [ "IA_XML_Strings", "d3/da5/struct_i_a___x_m_l___strings.html", null ],
    [ "IAAccelerationAnimationAttributes", "da/d89/struct_i_a_acceleration_animation_attributes.html", null ],
    [ "IAAllocationTrackingDelegate", "d5/d49/class_i_a_allocation_tracking_delegate.html", null ],
    [ "IAAllocationTrackingEvent", "da/de3/struct_i_a_allocation_tracking_event.html", null ],
    [ "IAApp", "da/d9d/struct_i_a_app.html", null ],
    [ "IAAppAttributes", "d6/d64/struct_i_a_app_attributes.html", null ],
    [ "IAAtlasAssetsAttributes", "d8/de9/struct_i_a_atlas_assets_attributes.html", null ],
    [ "IAButtonAttributes", "d1/d98/struct_i_a_button_attributes.html", null ],
    [ "IAColor", "db/d44/struct_i_a_color.html", null ],
    [ "IACompositedAnimationDelegate", "dd/d03/struct_i_a_composited_animation_delegate.html", null ],
    [ "IACompositedAnimationDelegateAttributes", "d4/d11/struct_i_a_composited_animation_delegate_attributes.html", null ],
    [ "IADate_s", "d3/df6/struct_i_a_date__s.html", null ],
    [ "IAFontInformationAttributes", "d2/df8/struct_i_a_font_information_attributes.html", null ],
    [ "IAFrameAnimationAttributes", "d2/d10/struct_i_a_frame_animation_attributes.html", null ],
    [ "IAFrameAnimationGroupAttributes", "db/dc5/struct_i_a_frame_animation_group_attributes.html", null ],
    [ "IAGlyphInformation", "d3/da9/struct_i_a_glyph_information.html", null ],
    [ "IAHashMapList", "d4/d64/struct_i_a_hash_map_list.html", null ],
    [ "IAImageAttributes", "d0/dbe/struct_i_a_image_attributes.html", null ],
    [ "IAImageContext", "d1/da1/struct_i_a_image_context.html", null ],
    [ "IAIntent", "d3/d9b/struct_i_a_intent.html", null ],
    [ "IAKeyValueElementAttributes", "df/d52/struct_i_a_key_value_element_attributes.html", null ],
    [ "IAKeyValueHashMap_onKeyValueParsedState", "d6/d19/struct_i_a_key_value_hash_map__on_key_value_parsed_state.html", null ],
    [ "IAMeassure", "d7/d22/struct_i_a_meassure.html", null ],
    [ "IAMemoryPoolElement", "d0/d7e/struct_i_a_memory_pool_element.html", null ],
    [ "IANotificationDelegate", "d3/d69/struct_i_a_notification_delegate.html", null ],
    [ "IANotificationEvent", "d0/dca/struct_i_a_notification_event.html", null ],
    [ "IAObject", null, [
      [ "IAAllocationTracker", "d0/df2/class_i_a_allocation_tracker.html", null ],
      [ "IAAllocationTrackerElement", "d0/d87/class_i_a_allocation_tracker_element.html", null ],
      [ "IAAllocationTrackingElement", "db/dea/class_i_a_allocation_tracking_element.html", null ],
      [ "IAArray", "d6/d4b/struct_i_a_array.html", null ],
      [ "IAArrayIterator", "d0/d88/struct_i_a_array_iterator.html", null ],
      [ "IAArrayList", "df/dd4/struct_i_a_array_list.html", null ],
      [ "IAArrayListIterator", "d0/d7b/struct_i_a_array_list_iterator.html", null ],
      [ "IAAtlasAssets", "d5/d39/struct_i_a_atlas_assets.html", null ],
      [ "IAAutoExpandingHashMap", "d8/d9a/struct_i_a_auto_expanding_hash_map.html", null ],
      [ "IABitmap", "db/de5/struct_i_a_bitmap.html", null ],
      [ "IABitmapManager", "db/d11/struct_i_a_bitmap_manager.html", null ],
      [ "IABuffer", "d0/d01/struct_i_a_buffer.html", [
        [ "IAArrayBuffer", "d4/d5a/struct_i_a_array_buffer.html", null ],
        [ "IAElementArrayBuffer", "d1/daf/struct_i_a_element_array_buffer.html", null ]
      ] ],
      [ "IACondition", "d4/d1e/class_i_a_condition.html", null ],
      [ "IADate", "dc/df8/class_i_a_date.html", null ],
      [ "IADrawable", "df/d4c/struct_i_a_drawable.html", [
        [ "IAAccelerationAnimation", "de/d06/struct_i_a_acceleration_animation.html", null ],
        [ "IACompositedAnimation", "da/d3b/struct_i_a_composited_animation.html", null ],
        [ "IADrawableRect", "dc/d4f/struct_i_a_drawable_rect.html", [
          [ "IAButton", "d1/dd0/struct_i_a_button.html", null ],
          [ "IAFrameAnimation", "d2/d0f/struct_i_a_frame_animation.html", null ],
          [ "IAFrameAnimationGroup", "da/ddc/struct_i_a_frame_animation_group.html", null ],
          [ "IAGraphicRect", "d9/d48/struct_i_a_graphic_rect.html", [
            [ "IAColorRect", "de/d85/struct_i_a_color_rect.html", null ],
            [ "IAImage", "dd/de1/struct_i_a_image.html", null ]
          ] ],
          [ "IAPauseAnimation", "df/d77/struct_i_a_pause_animation.html", null ]
        ] ],
        [ "IAGlyph", "da/d40/struct_i_a_glyph.html", null ]
      ] ],
      [ "IAFontAtlas", "db/d38/struct_i_a_font_atlas.html", [
        [ "IAColorableFontAtlas", "dc/d71/struct_i_a_colorable_font_atlas.html", null ]
      ] ],
      [ "IAFontInformation", "d4/df8/struct_i_a_font_information.html", null ],
      [ "IAHashMap", "d9/db4/struct_i_a_hash_map.html", null ],
      [ "IAHashMapIterator", "dd/d0b/struct_i_a_hash_map_iterator.html", [
        [ "IAAutoExpandingHashMapIterator", "d4/d7f/struct_i_a_auto_expanding_hash_map_iterator.html", null ]
      ] ],
      [ "IAKerningAmount", "d6/d5c/struct_i_a_kerning_amount.html", null ],
      [ "IAKeyValueElement", "d4/d0a/struct_i_a_key_value_element.html", null ],
      [ "IALock", "d1/d93/class_i_a_lock.html", null ],
      [ "IAMatrix44", "da/d6c/struct_i_a_matrix44.html", null ],
      [ "IAMemoryPool", "de/d18/struct_i_a_memory_pool.html", null ],
      [ "IAOverscrollingHandler", "df/d83/struct_i_a_overscrolling_handler.html", null ],
      [ "IAProgram", "d9/d5b/struct_i_a_program.html", [
        [ "IAColorRectProgram", "df/dc3/struct_i_a_color_rect_program.html", null ],
        [ "IAImageProgram", "d8/d1f/struct_i_a_image_program.html", null ]
      ] ],
      [ "IARecursiveLock", "d0/d93/class_i_a_recursive_lock.html", null ],
      [ "IAScrollingData", "d6/ddb/struct_i_a_scrolling_data.html", null ],
      [ "IAScrollView", "d7/da5/struct_i_a_scroll_view.html", null ],
      [ "IAShader", "d2/dc7/struct_i_a_shader.html", null ],
      [ "IAString", "de/d39/struct_i_a_string.html", null ],
      [ "IATexture", "d9/dee/struct_i_a_texture.html", null ],
      [ "IATouchHandler", "d6/d1e/struct_i_a_touch_handler.html", null ],
      [ "IAViewHolder", "de/de3/struct_i_a_view_holder.html", null ]
    ] ],
    [ "IAObjectInformation", "d8/d7f/struct_i_a_object_information.html", null ],
    [ "IAOffscreenFramebuffer", "d9/d3a/struct_i_a_offscreen_framebuffer.html", null ],
    [ "IAOpenGLResourceDelegate", "d1/dfe/struct_i_a_open_g_l_resource_delegate.html", null ],
    [ "IAOpenGLResourceDelegateAttributes", "dc/dc9/struct_i_a_open_g_l_resource_delegate_attributes.html", null ],
    [ "IAOpenGLResourceEvent", "d1/d8e/struct_i_a_open_g_l_resource_event.html", null ],
    [ "IAOverscrollingBehavior", "d1/de7/struct_i_a_overscrolling_behavior.html", null ],
    [ "IAPoint", "d9/def/struct_i_a_point.html", null ],
    [ "IAPos", "d3/d12/struct_i_a_pos.html", null ],
    [ "IAProgramAttribute", "d1/d35/struct_i_a_program_attribute.html", null ],
    [ "IARect", "d2/d47/struct_i_a_rect.html", null ],
    [ "IAScrollingData_TouchEvent", "d5/df3/struct_i_a_scrolling_data___touch_event.html", null ],
    [ "IAScrollViewAttributes", "d0/ddc/struct_i_a_scroll_view_attributes.html", null ],
    [ "IASize", "db/dfd/struct_i_a_size.html", null ],
    [ "IAStopwatch", "de/d79/struct_i_a_stopwatch.html", null ],
    [ "IATextureDelegate", "d1/d1e/struct_i_a_texture_delegate.html", null ],
    [ "IATextureDelegateAttributes", "de/dbe/struct_i_a_texture_delegate_attributes.html", null ],
    [ "IATextureSelection", "da/d7d/struct_i_a_texture_selection.html", null ],
    [ "IATextureSelectionData", "dc/dd1/struct_i_a_texture_selection_data.html", null ],
    [ "IATouch", "df/dd9/struct_i_a_touch.html", null ],
    [ "IATouchDelegate", "d1/d14/struct_i_a_touch_delegate.html", null ],
    [ "IATouchDelegateAttributes", "d9/d3b/struct_i_a_touch_delegate_attributes.html", null ],
    [ "IATrimmedRect", "da/dc1/struct_i_a_trimmed_rect.html", null ],
    [ "IAView", "d0/d8f/struct_i_a_view.html", null ],
    [ "IAViewAttributes", "d4/d32/struct_i_a_view_attributes.html", null ]
];